### ISSUE TITLE
Mining satchel rebalance and improvement

### ISSUE THREAD

**Issue by fluorescent-net** [discordia-space/CEV-Eris#1752]
- [ ] Transferring full mining satchel to ore box took about 7-10 seconds (w/out any progress bar) which is way too much even for so called "realism" purposes.
- [ ] Even full satchel easily fits your pocket. It shouldn't.
- [ ] Implement a possibility to examine satchel contents.
- [ ] Probably implement a progress bar on ore picking because sometimes it's hard to say if you actually picking ore (which tooks up to 2 seconds) or just lagging.

**Comment by NanakoAC** [comment]
1. Mining satchel doesnt take any time at all to transfer to ore box. I know because i was testing it extensively a few days ago. the entire contents are transferred instantly with a single click
2. I agree this is unrealistic, but would it be a huge pain for players if it were changed? 
3. Just open it like any normal bag, you can see inside. it's a bit unwieldy since you'll see like 50 little pieces of ore, but it works
4. I just added audio feedback to this, and it has always had text feedback that says you either picked something up, or failed to pick anything up. And, like 1, scooping things up with a bag is an action that happens instantly

it sounds like points 1 and 4 are just lag, i've not seen these happening. The russian server is far more populated though, possibly issues are exacerbated. Those actions are instant under normal conditions

**Comment by fluorescent-net** [comment]
> Mining satchel doesnt take any time at all to transfer to ore box. I know because i was testing it extensively a few days ago. the entire contents are transferred instantly with a single click.

That's weird. 
1) I expirienced this problem on barely populated server (5-7 players) and on completely empty as well.
2) I haven't expereinced any other possible lags on asteroid (movement lags, console interaction lags etc.) that I regularly expereince on main ship map.

I'll try to test it again on my local server and report the results.
