### ISSUE TITLE
Repair Stations

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#1764]
Normally whenever the ship is heavily damaged (or even lightly damaged, honestly), people think it's too much work to fix and call an evac shuttle to restart the round.

I don't like this, and i have an idea for an alternative. Automated repair stations. A place the ship could navigate to for repairs, to be fixed in an ultrafast time by clouds of nanobots. For a modest price of course.

But the practicality of it is the thing here. My idea is, these bots would work by directly reading the dmm file from disk. For each damaged tile, they'd look at the dmm, to see what originally should have been there, and restore the tile to its roundstart state, effortlessly fixing hull breaches, broken wires and pipe networks, and even irreplaceable machinery and normally un-buildable objects. (items would not be restored, only non-item objs)

A global list of bad (ie, potentially damaged) tiles would be kept. A tile would be added to this list whenever it gets shot, blown up, hit by a monster or meteor, etc. But generally not when manipulated with tools, to avoid wiping player constructed things

A modest upfront fee would be charged to begin repairs, based on the size of the bad tiles list.
A little nanobots mob would be spawned on each bad tile, and they'd read the dmm to restore that tile over a minute or two, then vanish (it's assumed they use themselves as building material)
For any bad tile on which no work was necessary, some of the fee would be refunded

The crux of the plan is, can you actually read the dmm like that?

**Comment by Voldirs** [comment]
I REALLY like that idea, that is unique and just good.
As for reading .dmm files, I think we could just have another hidden unsimmulated Eris z-level so bots could use kind of in-game reference

**Comment by ACCount12** [comment]
You totally can read from .dmm files on the go, that's how tgstation's map system works. They load the entire station from a .dmm after the round starts, so it should be possible to check select tiles in a .dmm and restore the walls and wiring from there.

Restoring most machinery and structures is too much, as it gives players an unlimited amount of anything that can be gained from a destructible, movable or deconstructable machine. There should be a whitelist to limit the repairs to airtight structure (basic floors, walls, windows and airlocks), communications (wiring and piping, possibly lights and APCs) and maybe some mission critical machines that can't be repaired in any other way.

The repairs would be barebones, intentionally. They shouldn't be perfect, but they should be enough to make the ship habitable after some light re-pressurization work.

I'm not sure if it's open source, but I've seen a system like that on a Traitor Deathmatch server. Tgstation also has station blueprints highlight what wiring and piping is _supposed_ to be, which may be related.

**Comment by NanakoAC** [comment]
> Restoring most machinery and structures is too much, as it gives players an unlimited amount of anything that can be gained from a destructible, movable or deconstructable machine. 

its not free, the ship would pay for the repairs. You can already buy materials at cargo, so there's not much practical difference. If you want to take your own ship apart then pay to have it rebuilt, go nuts

**Comment by ACCount12** [comment]
I don't think *all* materials are readily obtainable, and with how many machines there are on station? There would be exploits, guaranteed.

And it's not just that, it's also about making such repairs more of an emergency solution. They should restore ship's basic functions and repair communications that are tedious to redo by hand, but they shouldn't be perfect.

I also restored my comment you edited. For future reference: you can click "edited" to view full edit history, including the text.

**Comment by Wesreidau** [comment]
Having a shipyard the Captain can limp into to repair at is a good idea, and while currently the ship's budget is pretty close to infinite, there's no reason to keep it that way.

There is a real question as to what this does to technomancers. As a longtime engineer player, making full repairs that look exactly like, or better than, the damaged area is a point of pride. So there's a part of me that wants to do that. There's another part of me that occasionally looks at a problem and declares fuck it. The difference is the number of like-minded engineers and assistants helping with the repairs.

If the Captain pulls into the shipyard and was to get repairs, perhaps it could be priced and limited to specific subsystems. For example, it could fix pipes, cables, floor turfs, wall turfs, window turfs, all as seperate options with separate prices. The "nanite cloud" (I would almost rather the screens fade-to-black because nanite engineering might have unintended consequences) would then fix map elements in the given category. If the engineer team only needs a leg up on repairs, then they might request the hull get repaired, which would fix all the space-facing wall turfs and windows. Or they might get the pipe networks repaired after a blob. 

I would also make clear in lore that this isn't an automatic station but a Technomancer "lodge" in some hollowed-out asteroid, which of course, any decent technomancer aboard ship won't want to visit as a point of pride. One mechanic taking his car to another mechanic's shop and all.
