### ISSUE TITLE
Window spawners can fail 

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#1883]
![test](https://i.imgur.com/KrWRHgp.png)

When using force start, it's possible for window spawners to get interrupted and never complete initialization

possibly the master controller overhaul will fix this

**Comment by GrayRachnid** [comment]
The only way to fix this is to force initialization like this to happen during server booting instead of startup. Otherwise, this will always happen whenever you force start. Another option would be to force initialization when you hit force start, but that would make force start lock up the server as it quickly tries to initialize everything as quickly as possible.

I'm no coder, but this is how I think it would be if you think about it from a logical perspective.

**Comment by NanakoAC** [comment]
I disagree on both counts.

The third option,  is to make the force start button queue up a start as soon as possible, which is what the new master controller has done
