### ISSUE TITLE
List of objects that do not update open space properly

### ISSUE THREAD

**Issue by ghost** [discordia-space/CEV-Eris#2308]
I'll be populating this list as I find new entries, feel free to contribute more:

pipe meter
gas on turfs (sleep gas, plasma)
smoke effect from chems

**Comment by NanakoAC** [comment]
I'm confused, why is it up to an object to update this? What exactly is wrong with the pipe meter that causes an issue with openspace, what CAN go wrong?

Surely openspaces should update whenever a turf changes, and whenever any atom moves into or out of a turf under an openspace

**Comment by spaceplaceexplorer** [comment]
Objects can change their icon, icon_state, overlays, or anything that changes how they look, without moving or otherwise changing anything on a turf, or indicating to anything at all that they changed. This is completely internal to that object, and since there is no encapsulation anywhere for such changes, the object must call for update.

Which leads to this list, rather than making a wrapper for visual changes.
