### ISSUE TITLE
SUGG: Remove flamethrower from autolathe misc tools list

### ISSUE THREAD

**Issue by LagannPM** [discordia-space/CEV-Eris#2593]
It looks completely out of place

**Comment by Wesreidau** [comment]
Since you can craft them by hand, the autolathe isn't a restricting factor. However, flamethrowers are powerful tools in game for anti-fungus and anti-blob duties. This justifies them having some place in-game as a manufactured tool. In real life, they are considered agricultural or land management tools. Underbrush, back-burns, cane breaks, silkworm, bee and wasp hives, termites, gophers, snow and ice clearance, ragweed, horsetail...

Perhaps we should rename and re-describe the printed flamethrower to imply it is a common tool among the Technomancy, and rename and re-describe a handmade flamethrower to make clear it is quite possibly a weapon? Same performance being entirely fine.
