### ISSUE TITLE
OVERSIGHT: Various items can embedd but they really shouldn't

### ISSUE THREAD

**Issue by RandomColonist** [discordia-space/CEV-Eris#2824]
Title. For example, you can often find yourself in uneasy situation when your laser-guided diamond-edged sharpened circular saw embeds in the Fuhrer Roach. I think i don't need to explain why circular saw or any other similar instrument (combi drive, chainsaw) can't be embed. Either it need exeption that forbids embed_act (don't be mad i am dumb) from occurance or replace this behaviour with simple dropping of tool or flying off your hands.

**Comment by NanakoAC** [comment]
This is actually not at all correct. Tools with moving parts like a chainsaw can - and frequently do get stuck in things. In fact they are far, far more likely to do so than a hand tool because their cutting ability is dependant on their speed. When blades are spinning rapidly they can have enough power to cut into something, wedge there and stall, and then be unable to build up momentum to cut out. Serrated edges have a similar problem

Mechanics will be added to help alleviate this, but its working as intended for now
