### ISSUE TITLE
BUG: Crafting system problems

### ISSUE THREAD

**Issue by Coureere** [discordia-space/CEV-Eris#2828]
1. I believe that multiple structures starting anchored when constructed via crafting menu, which is unintended because you want it to be unwrenched/unscrewed for easy repositioning. Can confirm only on rails.
2. Craft doesn't respect direction that your character facing. It resulting in any construction facing south upon construction regardless your character or assembly positioning. It's bad because you can't turn modular console for example.
I'l add more if i'l encounter something.
3. Crafting system can't properly stack multiple material items. For example, when you crafting steel rods, it puts first in your hand and the rest on the ground below you. One by one. And you need to gather it yourself.
4. New crafting system is badly categorized. For example, there is like 6 entries for comfy chairs when it can be only one clickable button that leads to color menue. It's straight downgraid from old system, which had it.

**Comment by RandomColonist** [comment]
Updated.

**Comment by hyperioo** [comment]
I will try to fix some of those things. I will keep you updated.

**Comment by hyperioo** [comment]
**1.** I would need more details about which structures are concerned. Computer frames start unwrenched, same for AI turrets. Module consoles and machine frames start wrenched but you cannot move them anyway since wrench is used to deconstruct them. Only structure I found wrenched from the start is the bookshelf but I guess it's not very used. Maybe I'm missing some stuff.

**2.** Can confirm for modular console though it's not as worse as written in the issue. The direction depends on your direction but is inversed. If you're facing west the console spawns facing west too when it should spawn facing east (to have the keyboard on your side). Will fix that.

**3.** Already fixed by someone.

**4.** Can confirm, will see what I can do.

**Comment by hyperioo** [comment]
Can be closed. Fix PR #4852 and #4854 have been merged.
