### ISSUE TITLE
When blobcore is destroyed, strong blob don't vanish

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3026]
![image](https://user-images.githubusercontent.com/21274357/53555583-4657e300-3b53-11e9-86e8-10d09fa5707c.png)
Also, there some grammar stuff with their names, like - blob476.

**Comment by MrFoxik** [comment]
UPD. It vanish, but only after 10-15 minutes from blobcore is beign destroyed. Weird.

**Comment by NanakoAC** [comment]
working as intended. Blob parts stop growing or regenerating and instead take small amounts of constant damage until they die. The strong ones just have a ton of health

its designed so that the remnants of the blob fade out slowly and gracefully, gradually turning more and more transparent until they're eventually gone

you can whack it with something to make it go away faster if its a nuisance
