### ISSUE TITLE
Maint drone is captain card

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3219]
Maint drones can be used to open doors, if you pick up them in hands. Also, they really have some ID card-like features. You can hide your identity, and get name "maint drone", by hiding your face, with drone in your hands.

**Comment by XanderDox** [comment]
Gonna look into this.

**Comment by XanderDox** [comment]
Got the fix for it. Because Synths like drones do not carry ID cards, they have inherent ID-like properties to compensate and give them access.

This is OK if the drone is awake and active, because they can avoid being used as an ID - so drones that have an active player still inside them will still be able to be used as an ID card to open a door, because the drone itself does have access and if you held it up to the door it would realistically open.

The PR I'm going to do will make it so SSD/Ghosted drones will lose their access so they cannot be used as IDs.
