### ISSUE TITLE
[SUGG/MAP] Inspector and medspec access

### ISSUE THREAD

**Issue by DeLaFlash** [discordia-space/CEV-Eris#3413]
SUGG: give inspectors forensics access. a medspec can do all that an inspector can, while an inspector needs the medspec to do anything. operatives are too retarded to leave anyone alive for questioning, so inspectors are 100% useless and just exist for the coat and gun. medspec stay special because they have biology, inspectors become special because they can actually investigate a case on their own. especially nice for lowpop.

**Comment by fernandos33** [comment]
well but if that happens then buff thw skills jn medspec since if this happens eh will me a better pick in all cases.
cause so far inspector have better gun coat ammo. while medspec barely gets a gun and. even with the gun. he need to go to bay get medical tools like dylo and inaprov. plus inspector is more robust and etc. and medspec doesnt even have acces to surgery

**Comment by mistyLuminescence** [comment]
As of 21/7/19, the only access medspec has that inspector *doesn't* is medical_equip (used for medbay lockers and such). Inspector still has full access to forensics areas like the morgue.
