### ISSUE TITLE
Post humorous review of #4208

### ISSUE THREAD

**Issue by Garen7** [discordia-space/CEV-Eris#4239]
See: #4208 
@shazbot194 hey you missed some stuff and I'm not sure what you were going to do for some of this so I'm just @'ing you.
- - -
You defined DAMAGE_PISTOL twice and I'm not sure what the right value is
https://github.com/discordia-space/CEV-Eris/blob/e4c7c2e234d2b1ec41f278affae82bbeb1ee6561/code/modules/projectiles/projectile/bullettypes.dm#L16
- - -
There's a lot of undef's here that aren't defined im pretty sure
https://github.com/discordia-space/CEV-Eris/blob/e4c7c2e234d2b1ec41f278affae82bbeb1ee6561/code/modules/projectiles/projectile/bullettypes.dm#L222
- - -
## The rest are just consistency issues which can really be fixed by anyone
The idaho uses .35 now not .30, make sure you also fix the description when you fix the name
https://github.com/discordia-space/CEV-Eris/blob/02b2d8511f824922ea1a7a5ec39bd6cc76693c34/code/modules/projectiles/guns/projectile/automatic/idaho.dm#L2
- - -
This seems against convention, you use ".20" instead of "20 Rin" for the only other .20 gun the wintermute so I'm not sure which is right here
https://github.com/discordia-space/CEV-Eris/blob/02b2d8511f824922ea1a7a5ec39bd6cc76693c34/code/modules/projectiles/guns/projectile/automatic/z8.dm#L2
- - -
Should say ".35" not "35", also in the description
https://github.com/discordia-space/CEV-Eris/blob/02b2d8511f824922ea1a7a5ec39bd6cc76693c34/code/modules/research/designs/weapon.dm#L90
- - -
Missed this file
https://github.com/discordia-space/CEV-Eris/blob/4f96f3ad3acb16e6745e8be403fb9f3b9d7b7834/code/datums/autolathe/guns.dm
- - -
Should say .35 auto, not 10mm
https://github.com/discordia-space/CEV-Eris/blob/02b2d8511f824922ea1a7a5ec39bd6cc76693c34/code/modules/research/designs/weapon.dm#L27
- - -
Should say .35 auto not 9mm
https://github.com/discordia-space/CEV-Eris/blob/02b2d8511f824922ea1a7a5ec39bd6cc76693c34/code/modules/projectiles/guns/projectile/automatic.dm#L3
- - -
Should say .40 magnum not .357
https://github.com/discordia-space/CEV-Eris/blob/f1299887e1d81a46340de7356cc29d3b2b7c8033/code/modules/projectiles/guns/projectile/revolver/capgun.dm#L2
- - -
These probably doesn't matter but should probably be changed
https://github.com/discordia-space/CEV-Eris/blob/02b2d8511f824922ea1a7a5ec39bd6cc76693c34/code/modules/projectiles/guns/projectile.dm#L17
https://github.com/discordia-space/CEV-Eris/blob/02b2d8511f824922ea1a7a5ec39bd6cc76693c34/code/modules/projectiles/ammunition.dm#L184
- - -
Icon names still match old calibers
- - -
**When I get home I'll do a more thorough search**

**Comment by shazbot194** [comment]
Hey, sorry about missing some stuff, I had to remake this PR twice, and once was a complete redo, so I'm not too surprised that I missed some stuff. I will go down the list of things that I can answer. 

Pistol damage is meant to be 22, being equal to the old 9mm. I'm actually not sure how the second one got in there, but it is meant to be 22 damage. 

I'm not a coder, and don't know why things need to be undefined, nor did I ever see those when working on the code, so ya, 100% missed them.

I missed quite a few names mostly because they don't pop up or error when I didn't change them, and general typos. So my bad on this one, but in my defense, I was making this between tests.

I was told not to update icons, as that would make the PR take too long, and not offer any real benefit. This was planned to be done later already.

**Comment by SpadesSlick** [comment]
I'm redoing define part right now anyway.

**Comment by Garen7** [comment]
@shazbot194 its all good man no need to apologize mistakes happen, I just saw that stuff so I needed to make it known

**Comment by Garen7** [comment]
Gunna assume this was fixed cause it was a long time ago
