### ISSUE TITLE
[BUG] serbs cant dock at docking port anymore

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#4618]

**Comment by hyperioo** [comment]
Shuttle cannot go to the docking port destination because there would be a collision with a maintenance room (see red crosses in the bottom line of the picture).

![alt text](https://media.discordapp.net/attachments/684117567253643323/713084836381982890/shuttle_dock.png?width=601&height=610)

I guess this room has been added recently and the mapper forgot to shift the docking port to the left to take into account this new room. The docking port has to be extended six tiles to the left and the _Docking Port_ landmark tag must be moved as well.

![alt text](https://media.discordapp.net/attachments/684117567253643323/713111790577516544/shuttle_dock2.png?width=871&height=610)

I've talked about it in The Shaft room of the discord.
