### ISSUE TITLE
Letter "я" in dream daemon log

### ISSUE THREAD

**Issue by Broda1** [discordia-space/CEV-Eris#833]
![image](https://user-images.githubusercontent.com/5676099/27193841-d564c7cc-5219-11e7-8c6b-aebd33e254d1.png)

**Comment by KuzyXD** [comment]
Need to translate into English.

**Comment by Quardbreak** [comment]
Probably already fixed by someone.

**Comment by silentenemy** [comment]
This is related to BYOND printing out WinAPI error messages (https://msdn.microsoft.com/en-us/library/cc231199.aspx). Because these are localized (and therefore include я) and BYOND can't handle я without troubles, we have such bug, and it unfortunately can't be fixed Eris-side.

Closing due to impossibility of fix
